name: 'Setup project'
description: 'Sets up project and its dependencies'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: https://npm.pkg.github.com
        cache: 'pnpm'
        cache-dependency-path: './pnpm-lock.yaml'

    - run: pnpm install --frozen-lockfile
