name: Release

on:
  push:
    branches: ['main']

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#      - name: Create Release Pull Request or Publish to npm
#        id: changesets
#        uses: changesets/action@v1
#        with:
#          publish: pnpm release
#          version: pnpm next-version
#        env:
#          GITHUB_TOKEN: ${{ secrets.GIT_DEPLOY_KEY }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
