name: Update dependencies

env:
  NODE_VERSION: 18

on:
  schedule:
    - cron: 0 16 * * * # every day at 16pm
  workflow_dispatch:

jobs:
  updateDependencies:
    name: 'Update dependencies'
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup project'
        uses: ./.github/actions/setup-project

      - name: 'Update all dependencies'
        run: pnpm -r update --latest

      - name: 'Check code quality'
        uses: ./.github/actions/check-quality

      - name: 'Prepare git'
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "Github Actions"
          git branch -u origin/main main

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Check for existing PR
        id: check_open_pr
        run: |
          pr_number=$(gh pr list --state open --label "update-deps" --json number --jq '.[0].number')
          echo "pr_number=${pr_number:-0}" >> "$GITHUB_OUTPUT"

      - name: Create PR if not exists
        id: create_pr
        if: ${{ steps.check_open_pr.outputs.pr_number == 0 }}
        run: |
          # Prepare git
          git config --global user.email "noreply@github.com"
          git config --global user.name "Github Actions"
          git branch -u origin/main main
          # Create branch, commit and PR
          branch_name="update-deps/$(date +'%Y%m%d%H%M%S')"
          git checkout -b $branch_name
          gir add -A
          git commit -m "chore: update dependencies"
          git push origin $branch_name
          gh pr create --title "chore: update dependencies" --base main --head $branch_name --label "update-deps"
